### ISSUE TITLE
Installing trepan3k-0.8.10 from PyPI  can fail due to incompatible xdis requirement

### ISSUE THREAD

**Issue by zed** [rocky/python3-trepan#23] opened 2020-03-08 09:10 UTC
```
$ pip install trepan3k                                                                             ~   
Collecting trepan3k                                                                                      
  Using cached trepan3k-0.8.10-py3-none-any.whl (338 kB)                                                 
Collecting uncompyle6>=3.4.1
  Using cached uncompyle6-3.6.4-py3-none-any.whl (309 kB)
...
Collecting xdis<4.1.0,>=4.0.4
  Using cached xdis-4.0.4-py37-none-any.whl (94 kB)
...
ERROR: uncompyle6 3.6.4 has requirement xdis<4.3.0,>=4.2.2, but you'll have xdis 4.0.4 which is incompatible.
...
```
Installing from master works fine:
```
$ pip install -e git+ssh://git@github.com/rocky/python3-trepan.git#egg=trepan3k
...
Collecting xdis<4.3.0,>=4.2.0
  Downloading xdis-4.2.2-py37-none-any.whl (101 kB)
...
```

**Comment by rzuckerm** [comment] 2020-03-16 12:24
I don't particularly want to install the package using the latest code in GitHub since this does not give any type of build reproducibility. I got around this by upgrading xdis separately after installing trepan3k (`pip install trepan3k==0.8.10; pip install -U xdis`). Please release whatever package needs to be updated as soon as you can so that I don't have to do this anymore in my docker file.

**Comment by rocky** [comment] 2020-03-16 12:42
@rzuckerm Ok. Thanks for the info. I'll probably update soon. 

But this reminds me. I use the ratings of a project to help decide what to work on when I have free time. The rating of this project doesn't even appear in the list of the top 6 projects in https://github.com/rocky/, thus it is of less importance than any of those listed there. 

If you think that priority listed in the link above is the right one, then great. However iif you think this project have in a docker file should be in the top 6 then perhaps you should upvote it.

**Comment by rocky** [comment] 2020-03-16 22:14
I think release 0.8.11 addresses all the problems. If not close this, if so let me know. And if no response, I'll close this in a day or so.

**Comment by rzuckerm** [comment] 2020-03-17 13:05
It's working for me. Thanks, @rocky !

**Comment by rocky** [comment] 2020-03-17 14:58
Good - closing then. 

However keep in mind what I wrote about project priorities.

**Closed by rocky** 2020-03-17 14:58 UTC

**Comment by abliss** [comment] 2020-04-22 03:37
Not sure if this is related, but I just tried to use trepan3k for the first time, and 0.8.11 seems to have some kind of broken dependency regarding xdis:
```python3 -m pip install trepan3k 
trepan3k my_script.py
Starting FIFO server for process 11442.                                                                                                                               Traceback (most recent call last):                                                                                                                                      File "/home/abliss/proj/sandstorm/matrix/env/bin/trepan3k", line 8, in <module>                                                                                         sys.exit(main())                                                                                                                                                    File "/home/abliss/proj/sandstorm/matrix/env/lib/python3.6/site-packages/trepan/cli.py", line 71, in main                                                               dbg = Mdebugger.Trepan(dbg_opts)
  File "/home/abliss/proj/sandstorm/matrix/env/lib/python3.6/site-packages/trepan/debugger.py", line 285, in __init__                                                     import trepan.lib.core as Mcore                                                                                                                                     File "/home/abliss/proj/sandstorm/matrix/env/lib/python3.6/site-packages/trepan/lib/core.py", line 32, in <module>                                                      from trepan.lib import breakpoint, default, stack as Mstack
  File "/home/abliss/proj/sandstorm/matrix/env/lib/python3.6/site-packages/trepan/lib/stack.py", line 21, in <module>
    from trepan.lib.deparse import deparse_offset
  File "/home/abliss/proj/sandstorm/matrix/env/lib/python3.6/site-packages/trepan/lib/deparse.py", line 7, in <module>
    from uncompyle6.semantics.linemap import code_deparse_with_map
  File "/home/abliss/proj/sandstorm/matrix/env/lib/python3.6/site-packages/uncompyle6/__init__.py", line 48, in <module>                                                  import uncompyle6.semantics.pysource                                                                                                                                File "/home/abliss/proj/sandstorm/matrix/env/lib/python3.6/site-packages/uncompyle6/semantics/pysource.py", line 132, in <module>
    from xdis import iscode                                                                                                                                           ImportError: cannot import name 'iscode'
```

**Comment by rocky** [comment] 2020-04-22 03:54
@abliss  What does `pip freeze` report?

**Comment by abliss** [comment] 2020-04-22 14:34
I posted my `pip freeze` output (after force-upgrading xdis) here:
https://gist.github.com/abliss/bb0a4a1c935b6694e11ac462408fdacd
(I should perhaps mention that I only barely understand how pip works at
all, so I apologize if I'm wasting your time.)

Thanks for taking a look!
