### ISSUE TITLE
why Trenpan3k is struggling to develop users?

### ISSUE THREAD

**Issue by dev590t** [rocky/python3-trepan#39] opened 2022-06-02 22:39 UTC
I discover Trenpan3k. Its specification is interesting. But I don't found any user experience about it(e.g. blog).

why Trenpan3k is struggling to develop users?
Because Trenpan3k  isn't ready to use in production, it still has some bug? Or because it miss some feature compare to other debugger?

**Comment by rocky** [comment] 2022-06-05 15:37
At this point, I am not "struggling" to develop users. I have used this for myself a long long while, and it has a lot of things that I miss when I try to use other debuggers. It is production ready in the sense has fewer bugs/misfeatures than pdb and I use it in environments where I work code that others and myself consider "production". 

In general, there doesn't seem to be much interest in Python debuggers.  So you may find Python debugging as part of a discussion on IDEs.

But there are companies and large organizations that do that and so _they_  devote time  to publicizing that and writing Blogs. In the case of say JetBrains, they have based their work on a Ruby debugger core that I contributed and maintained for a while. And this code is basically a follow-on to that.

Lack of interest in debuggers is not exclusive to Python, although in the beginning I got a bit of attitude from Python community about how you don't need a debugger. One of may favorites is https://groups.google.com/g/comp.lang.python/c/kMvNA_NylKE/m/RkgdSmXerToJ

(In the early days of Python there was a lot of attitude in Python where if something was hard to do or wasn't supported, instead of acknowledging the difficulty and deficience the reply was instead "I know that you don't need that". ) 

I have written other debuggers where in some cases (such as for GNU make, zsh, bash, and ksh) it is the _only_ debugger available. Well, there are wrappers around these that provide support in say VSCode, but the underlying debugger is still the one I wrote. 

And I would not say those are popular as well in the sense that you'll find that blogs on them or discussion other than possibly what I've written. 

If also feels to me that pdb has borrowed, or implemented a number of ideas that were first explored here. For example pdb originally did _no_ checking on whether the line you set a breakpoint had code associated with it. This debugger checks to see that there is the line has an actual line number in it associated in the code. Later pdb's did this hack where a regexp scanned the source code to see if it was blank or started with a comment. What this debugger does is accurate whereas what pdb is a hack that works I suppose a lot of the time, _if_ the source code is available. 

My aim was to do something like this _well_, not haphazardly. However for most people 80% is good enough. So you'll find blogs on how to get around the 20% deficiencies. See
*  https://stackoverflow.com/questions/48029399/can-i-make-python-tell-me-on-exactly-which-character-causes-an-error/66786908#66786908 
* https://stackoverflow.com/questions/32486204/debugging-python-bytecode-when-source-is-not-available/66786726#66786726
* https://stackoverflow.com/questions/61296540/python-debugger-pdb-navigating-through-multi-module-code-using-pdb/61313306#61313306

The people who lose out on not having good debuggers are the people who work across many languages. For example, systems administrators, devops, reverse engineers fall into this category.  However the people who provide debuggers are language folks and often focused only on that particular programming language. So if the debugger is different from others, it is not a bother to the writer because that debugger for that language is the only one that they care about. 

As for this particular code, it is in need of rewrite to use the more recent breakpoint API, maybe use `prompt_toolkit` which is more featureful than Readline, figure out how to hook into a debugging protocol for remote execution and so on. 

However I have so many other things I am interested in that I live with the warts, or fix the ones that most annoy me. 

But in closing I should mention, enough about what this project. If there is an open-source project that you are interested in and you don't find blogs or whatever, if the project is useful write blogs. Or if there is a feature missing or a wart here that annoys you, fix it and put in a PR.  Open source used to be about community development. Nowadays it feels more like hey what can I get this guy to do for me.

**Comment by rocky** [comment] 2022-06-05 15:38
The issue tracker was intended for bugs, not discussions. I think github now has a separate space for discussions.

**Closed by rocky** 2022-06-05 15:38 UTC

**Comment by dev590t** [comment] 2022-06-16 09:18
Thank you, your answer is very informative.

**Comment by rocky** [comment] 2022-06-16 09:37
Now it is your turn to try to be helpful :-)

**Comment by dev590t** [comment] 2022-06-16 11:28
Of course, I just intend to write a blog about it, after testing trenpan3k and to be convinced.
